import {MediaEnum} from "../interfaces/Media.interface";

export const initialMedia = {
    id: 0,
    type: MediaEnum.All,
    popularity: '',
    poster: '',
    title: '',
    synopsis: '',
    releaseDate: '',
    backdropCover: '',
    genres: [],
    originalTitle: '',
    runtime: 0,
    status: '',
    tagline: '',
    voteAverage: 0,
    voteCount: 0,
    trailer: {},
    actors: [],
    directors: [],
    recommendations: [],
    logo: {},
    rating: 0,
    favorite: false,
    watchlist: false,
    seasons: [],
    loading: false,
};